//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GCT_PROGRAMACION_MEDICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GCT_PROGRAMACION_MEDICA()
        {
            this.T_GG_EMPLEADO = new HashSet<T_GG_EMPLEADO>();
        }
    
        public string idProgramcacion { get; set; }
        public int prestaciones { get; set; }
        public int disPrestaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime horaInicio { get; set; }
        public System.DateTime horaFin { get; set; }
        public string anotaciones { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public string codBien { get; set; }
    
        public virtual T_GG_INMUEBLE T_GG_INMUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPLEADO> T_GG_EMPLEADO { get; set; }
    }
}
