//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GDA_HISTORIA_CLINICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GDA_HISTORIA_CLINICA()
        {
            this.T_GUQ_SOLICITUD_UCI = new HashSet<T_GUQ_SOLICITUD_UCI>();
            this.T_GG_EMPLEADO = new HashSet<T_GG_EMPLEADO>();
        }
    
        public int nroHistoriaClinica { get; set; }
        public string diagnóstico { get; set; }
        public short idPaciente { get; set; }
        public string idPersona { get; set; }
    
        public virtual T_GDA_PACIENTE T_GDA_PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_SOLICITUD_UCI> T_GUQ_SOLICITUD_UCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPLEADO> T_GG_EMPLEADO { get; set; }
    }
}
