//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GG_PERSONA()
        {
            this.T_GDA_PACIENTE = new HashSet<T_GDA_PACIENTE>();
            this.T_GG_EMPLEADO = new HashSet<T_GG_EMPLEADO>();
            this.T_GG_EMPRESA = new HashSet<T_GG_EMPRESA>();
        }
    
        public string idPersona { get; set; }
        public string dirPersona { get; set; }
        public string telPersona { get; set; }
        public string emailPersona { get; set; }
        public string idTipoPersona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GDA_PACIENTE> T_GDA_PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPLEADO> T_GG_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPRESA> T_GG_EMPRESA { get; set; }
        public virtual T_GG_TIPO_PERSONA T_GG_TIPO_PERSONA { get; set; }
    }
}
