//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GG_EMPRESA()
        {
            this.T_GG_MUEBLE = new HashSet<T_GG_MUEBLE>();
            this.T_GMP_RESERVA_SERVICIO = new HashSet<T_GMP_RESERVA_SERVICIO>();
        }
    
        public string idEmpresa { get; set; }
        public int nroRuc { get; set; }
        public string razonsocial { get; set; }
        public string idPersona { get; set; }
    
        public virtual T_GG_PERSONA T_GG_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_MUEBLE> T_GG_MUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GMP_RESERVA_SERVICIO> T_GMP_RESERVA_SERVICIO { get; set; }
    }
}
