//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_MUEBLE
    {
        public string dscFunción { get; set; }
        public string dscAplicacionMedica { get; set; }
        public short garantia { get; set; }
        public string tipoMueble { get; set; }
        public string idModelo { get; set; }
        public string idEmpresa { get; set; }
        public string codBien { get; set; }
        public string idPersona { get; set; }
    
        public virtual T_GG_BIEN T_GG_BIEN { get; set; }
        public virtual T_GG_EMPRESA T_GG_EMPRESA { get; set; }
        public virtual T_GG_MODELO T_GG_MODELO { get; set; }
    }
}
