//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_INMUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GG_INMUEBLE()
        {
            this.T_GCT_PROGRAMACION_MEDICA = new HashSet<T_GCT_PROGRAMACION_MEDICA>();
            this.T_GUQ_CAMA = new HashSet<T_GUQ_CAMA>();
            this.T_GUQ_RESERVA_SALA_OPERACIÓN = new HashSet<T_GUQ_RESERVA_SALA_OPERACIÓN>();
        }
    
        public string dscTipoInmueble { get; set; }
        public bool estado { get; set; }
        public string codBien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GCT_PROGRAMACION_MEDICA> T_GCT_PROGRAMACION_MEDICA { get; set; }
        public virtual T_GG_BIEN T_GG_BIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_CAMA> T_GUQ_CAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_RESERVA_SALA_OPERACIÓN> T_GUQ_RESERVA_SALA_OPERACIÓN { get; set; }
    }
}
