//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GG_EMPLEADO()
        {
            this.T_GCT_PROGRAMACION_MEDICA = new HashSet<T_GCT_PROGRAMACION_MEDICA>();
            this.T_GUQ_TURNO_MEDICO = new HashSet<T_GUQ_TURNO_MEDICO>();
        }
    
        public int idEmpleado { get; set; }
        public string nroDni { get; set; }
        public string nomEmpleado { get; set; }
        public System.DateTime fecIngreso { get; set; }
        public string dscCargo { get; set; }
        public string dscProfesion { get; set; }
        public int idEspecialidad { get; set; }
        public int idArea { get; set; }
        public double costoHora { get; set; }
        public string stdEmplead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GCT_PROGRAMACION_MEDICA> T_GCT_PROGRAMACION_MEDICA { get; set; }
        public virtual T_GDA_ESPECIALIDAD__MEDICA T_GDA_ESPECIALIDAD__MEDICA { get; set; }
        public virtual T_GUQ_AREA T_GUQ_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_TURNO_MEDICO> T_GUQ_TURNO_MEDICO { get; set; }
    }
}
