//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GMP_BITACORA_INCIDENCIA
    {
        public int idBitacora { get; set; }
        public string tipoIncidencia { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string descripcion { get; set; }
        public string idEmpleado { get; set; }
        public string idPersona { get; set; }
    
        public virtual T_GG_EMPLEADO T_GG_EMPLEADO { get; set; }
    }
}
