//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GMP_RESERVA_SERVICIO
    {
        public string idReserva { get; set; }
        public System.DateTime fecReserva { get; set; }
        public System.DateTime horReserva { get; set; }
        public string tipoAtencion { get; set; }
        public string tipoCliente { get; set; }
        public string estado { get; set; }
        public string idServicio { get; set; }
        public string idEmpresa { get; set; }
        public string idEmpleado { get; set; }
        public short idPaciente { get; set; }
        public string idPersona { get; set; }
        public string T_GG_EMPLEADO_idPersona { get; set; }
        public string T_GDA_PACIENTE_idPersona { get; set; }
    
        public virtual T_GDA_PACIENTE T_GDA_PACIENTE { get; set; }
        public virtual T_GG_EMPLEADO T_GG_EMPLEADO { get; set; }
        public virtual T_GG_EMPRESA T_GG_EMPRESA { get; set; }
        public virtual T_GMP_SERVICIO_SALUD T_GMP_SERVICIO_SALUD { get; set; }
    }
}
