//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GMP_SERVICIO_SALUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GMP_SERVICIO_SALUD()
        {
            this.T_GDA_ESPECIALIDAD__MEDICA = new HashSet<T_GDA_ESPECIALIDAD__MEDICA>();
            this.T_GMP_RESERVA_SERVICIO = new HashSet<T_GMP_RESERVA_SERVICIO>();
            this.T_GMP_SERVICIO_SALUD1 = new HashSet<T_GMP_SERVICIO_SALUD>();
            this.T_GMP_SERVICIO_SALUD11 = new HashSet<T_GMP_SERVICIO_SALUD>();
        }
    
        public string idServicio { get; set; }
        public string tipoServicio { get; set; }
        public string nomServicio { get; set; }
        public string T_GMP_SERVICIO_SALUD_idServicio { get; set; }
        public string COL_0 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GDA_ESPECIALIDAD__MEDICA> T_GDA_ESPECIALIDAD__MEDICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GMP_RESERVA_SERVICIO> T_GMP_RESERVA_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GMP_SERVICIO_SALUD> T_GMP_SERVICIO_SALUD1 { get; set; }
        public virtual T_GMP_SERVICIO_SALUD T_GMP_SERVICIO_SALUD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GMP_SERVICIO_SALUD> T_GMP_SERVICIO_SALUD11 { get; set; }
        public virtual T_GMP_SERVICIO_SALUD T_GMP_SERVICIO_SALUD3 { get; set; }
    }
}
