//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_INSUMO_TIPOOPERACION
    {
        public int idOperación { get; set; }
        public int idInsumo { get; set; }
        public int cantidad { get; set; }
    
        public virtual T_GUQ_INSUMO T_GUQ_INSUMO { get; set; }
        public virtual T_GUQ_TIPO_OPERACIÓN T_GUQ_TIPO_OPERACIÓN { get; set; }
    }
}
