//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_CAMA
    {
        public int idCama { get; set; }
        public int idModelo { get; set; }
        public string estado { get; set; }
    
        public virtual T_GG_MODELO T_GG_MODELO { get; set; }
    }
}
