//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_SOLICITUD_UCI
    {
        public string idSolicitud { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public string idRegistro { get; set; }
        public int nroHistoriaClinica { get; set; }
    
        public virtual T_GDA_HISTORIA_CLINICA T_GDA_HISTORIA_CLINICA { get; set; }
        public virtual T_GUQ_INGRESO_SALIDA_PACIENTE T_GUQ_INGRESO_SALIDA_PACIENTE { get; set; }
    }
}
