//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_INGRESO_SALIDA_PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_INGRESO_SALIDA_PACIENTE()
        {
            this.T_GUQ_SOLICITUD_UCI = new HashSet<T_GUQ_SOLICITUD_UCI>();
        }
    
        public string idRegistro { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaTraslado { get; set; }
        public string motivo { get; set; }
        public System.DateTime mes { get; set; }
        public string idModelo { get; set; }
    
        public virtual T_GUQ_CAMA T_GUQ_CAMA { get; set; }
        public virtual T_GUQ_ESTADÍSTICA_RECURSOS T_GUQ_ESTADÍSTICA_RECURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_SOLICITUD_UCI> T_GUQ_SOLICITUD_UCI { get; set; }
    }
}
