//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_RESERVA_SALA_OPERACIÓN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_RESERVA_SALA_OPERACIÓN()
        {
            this.T_GUQ_TIPO_OPERACIÓN = new HashSet<T_GUQ_TIPO_OPERACIÓN>();
            this.T_GG_EMPLEADO = new HashSet<T_GG_EMPLEADO>();
        }
    
        public string idReserva { get; set; }
        public int duración { get; set; }
        public System.DateTime día { get; set; }
        public System.DateTime hora { get; set; }
        public string estado { get; set; }
        public System.DateTime mes { get; set; }
        public short idPaciente { get; set; }
        public string codBien { get; set; }
        public string idPersona { get; set; }
    
        public virtual T_GDA_PACIENTE T_GDA_PACIENTE { get; set; }
        public virtual T_GG_INMUEBLE T_GG_INMUEBLE { get; set; }
        public virtual T_GUQ_ESTADÍSTICA_RECURSOS T_GUQ_ESTADÍSTICA_RECURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_TIPO_OPERACIÓN> T_GUQ_TIPO_OPERACIÓN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPLEADO> T_GG_EMPLEADO { get; set; }
    }
}
