//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_ESTADÍSTICA_RECURSOS
    {
        public int idEstadisticaRecurso { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public int idArea { get; set; }
        public double montoHistórico { get; set; }
        public Nullable<int> idPartida { get; set; }
    
        public virtual T_GUQ_AREA T_GUQ_AREA { get; set; }
        public virtual T_GUQ_PARTIDA T_GUQ_PARTIDA { get; set; }
    }
}
