//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_INGRESO_SALIDA_PACIENTE
    {
        public int idRegistro { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaTraslado { get; set; }
        public string motivo { get; set; }
        public int idSolicitud { get; set; }
    
        public virtual T_GUQ_SOLICITUD_UCI T_GUQ_SOLICITUD_UCI { get; set; }
    }
}
