//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_TIPO_OPERACIÓN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_TIPO_OPERACIÓN()
        {
            this.T_GUQ_RESERVA_SALA_OPERACIÓN = new HashSet<T_GUQ_RESERVA_SALA_OPERACIÓN>();
        }
    
        public string idOperación { get; set; }
        public string dscTipoOperación { get; set; }
        public string insumos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_RESERVA_SALA_OPERACIÓN> T_GUQ_RESERVA_SALA_OPERACIÓN { get; set; }
    }
}
