//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_SOLICITUD_UCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_SOLICITUD_UCI()
        {
            this.T_GUQ_INGRESO_SALIDA_PACIENTE = new HashSet<T_GUQ_INGRESO_SALIDA_PACIENTE>();
        }
    
        public int idSolicitud { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public int nroHistoriaClinica { get; set; }
    
        public virtual T_GDA_HISTORIA_CLINICA T_GDA_HISTORIA_CLINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_INGRESO_SALIDA_PACIENTE> T_GUQ_INGRESO_SALIDA_PACIENTE { get; set; }
    }
}
