//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_PARTIDA
    {
        public string idPartida { get; set; }
        public string dscPartida { get; set; }
        public bool tipoPartida { get; set; }
        public Nullable<System.DateTime> año { get; set; }
    
        public virtual T_GUQ_PRESUPUESTO T_GUQ_PRESUPUESTO { get; set; }
    }
}
